{"dfs.nameservices": ["mycluster"], "dfs.namenode.rpc-address.mycluster.nn2": ["node2:8020"], "dfs.datanode.data.dir": ["/data/hadoopdataspace"], "dfs.namenode.shared.edits.dir": ["qjournal://node1:8485;node2:8485;node3:8485/mycluster"], "dfs.ha.fencing.ssh.connect-timeout": ["30000"], "dfs.namenode.http-address.mycluster.nn1": ["node1:50070"], "dfs.datanode.failed.volumes.tolerated": ["3"], "dfs.namenode.http-address.mycluster.nn2": ["node2:50070"], "dfs.client.failover.proxy.provider.mycluster": ["org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"], "dfs.permissions.superusergroup": ["hadoop"], "dfs.journalnode.edits.dir": ["/data/1/dfs/jn"], "dfs.namenode.rpc-address.mycluster.nn1": ["node1:8020"], "dfs.ha.fencing.methods": ["sshfence"], "dfs.namenode.name.dir": ["/data/hadoopnamespace"], "dfs.ha.namenodes.mycluster": ["nn1,nn2"], "dfs.name.dir": ["/var/lib/hadoop-hdfs/cache/hdfs/dfs/name"], "dfs.webhdfs.enabled": ["true"], "dfs.ha.fencing.ssh.private-key-files": ["/home/nodefence/.ssh/id_rsa"]}